name = circuits_support
title = Circuits Support
description = Adds circuits support for other mods.
depends = circuits
optional_depends = doors, default, mesecons
textdomain = circuits
min_minetest_version = 5.0.0
