name: Luacheck

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  luacheck:
    runs-on: ubuntu-latest

    steps:
       - name: Clone repository
         uses: https://code.forgejo.org/actions/checkout@v4

       - name: Install luacheck
         run: sudo apt-get update && sudo apt-get install -y lua-check

       - name: Run luacheck
         run: luacheck --config ./.luacheckrc .