name: Luacheck

on:
  push:
    branches:
      - master
      - main
    paths:
      - "**.lua"
  pull_request:
    paths:
      - "**.lua"

jobs:
  luacheck:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: https://code.forgejo.org/actions/checkout@main

      - name: Install luacheck
        uses: https://github.com/lunarmodules/luacheck@master
