circuits.modpath("/src/button.lua")
circuits.modpath("/src/pressure_plate.lua")
circuits.modpath("/src/inverter.lua")
circuits.modpath("/src/entity_detector.lua")
circuits.modpath("/src/player_detector.lua")
circuits.modpath("/src/solar_panel.lua")
circuits.modpath("/src/lever.lua")
circuits.modpath("/src/laser_detector.lua")
